# docs here: https://squidfunk.github.io/mkdocs-material/

site_name: Energizer
site_url: https://pietrolesci.github.io/energizer
repo_url: https://github.com/pietrolesci/energizer
repo_name: pietrolesci/energizer
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - About: about.md
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono

  #logo: assets/logo.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode   
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.tabbed:
    - alternate_style: true 
  - pymdownx.tasklist:
    - custom_checkbox: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta

plugins:
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - energizer
extra:
  version:
    provider: mike
    default: stable

  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pietro_lesci
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pietrolesci
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/pietrolesci/
      name: Github
    - icon: material/email
      link: "mailto:pietrolesci@outlook.com"
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - Pietro Lesci
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
