name: publish docs
on:
  workflow_dispatch:      

jobs:
  deploy:
    
    name: Publish documentation
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-versions: [3.9]
    
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build documentation
        run: poetry install -E doc
          
      - name: Publish docs
        run: poetry run mkdocs gh-deploy --force
